id: P004224
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5180
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་གདམས་སྐོར་གཅེས་བཏུས།
  author: ''
  volumes:
    2bc92c088635470f92f725479e63e895:
      image_group_id: I3CN5182
      title: ''
      volume_number: 1
      total_pages: 89
